---
title: "Code-Along-and-Challenge-9"
author: "Phua Zong Yao"
date: "2023-10-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

# START OF CODE ALONG 9


# Slide 8
# Tidy vs Non-Tidy

```{r, eval=T,echo=TRUE}
library(tidyverse)
tidydata <- tribble(
  ~country, ~year, ~cases, ~population,
  "Afghanistan", 1999, 745, 19987071,
"Afghanistan", 2000, 2666, 20595360,
"Brazil", 1999, 37737, 172006362,
"Brazil", 2000, 80488, 174504898,
"China", 1999, 212258, 1272915272,
"China", 2000, 213766, 1280428583)

tidydata

```


```{r, eval=T,echo=TRUE}
nontidydata <- tribble(
  ~country,~year,~rate, 
  "Afghanistan", 1999, "745/19987071",
"Afghanistan", 2000, "2666/20595360",
"Brazil", 1999, "37737/172006362",
"Brazil", 2000, "80488/174504898",
"China", 1999, "212258/1272915272",
"China", 2000, "213766/1280428583"
)

nontidydata

```
# Slide 11 
# Tidy-ing data: Example 1

```{r, eval=T,echo=TRUE}

nontidydata

```


```{r, eval=T,echo=TRUE}

tidieddata <- nontidydata %>% 
  separate(rate, into = c("cases", "population"),
                                     sep = "/")

tidieddata

```

# Slide 12
# Tidy-ing data: Example 1

```{r, eval=T,echo=TRUE}

newtidieddata <- tidieddata %>% 
  pivot_longer(
    cols = cases:population,
    names_to = "measurement",
    values_to = "value"
  )

newtidieddata

```

# Slide 14 
# Tidy-ing data: Example 2

```{r, eval=T,echo=TRUE}

df <- tribble(
  ~id, ~bp1, ~bp2,
  "A",100,120,
  "B",140,115,
  "C",120,125
)

df

```


```{r, eval=T,echo=TRUE}

df %>%
  pivot_longer(
    cols = bp1:bp2,
    names_to = "measurement",
    values_to = "value"
  )

```

# Slide 18
# Reshaping Data: Example 3

```{r, eval=T,echo=TRUE}

newtidieddata

```

```{r, eval=T,echo=TRUE}

newtidieddata %>%
  pivot_wider(names_from = "measurement",
              values_from = "value")

```


# Slide 19
# Reshaping Data: Example 4

```{r, eval=T,echo=TRUE}

df <- tribble(
  ~id, ~measurement, ~value,
  "A",        "bp1",    100,
  "B",        "bp1",    140,
  "B",        "bp2",    115,
  "A",        "bp2",    120,
  "A",        "bp3",    105
  
)
df

```

```{r, eval=T,echo=TRUE}

df %>% 
  pivot_wider(
    names_from = "measurement",
    values_from = "value"
  )

```

# START OF CHALLENGE 9

# PART 1

```{r, eval=T,echo=TRUE}

library(tidyverse)

my_data <- billboard %>%
  pivot_longer(cols = starts_with("wk"),
               names_to = "week",
               values_to = "rank",
               values_drop_na = TRUE) %>% 
mutate(week = parse_number(week))

my_data

# plotting the data 

ggplot(my_data,aes(x = week, y = rank)) +
  geom_line() +
  labs(x = "Week", y = "Rank")

```

# PART 2

```{r, eval=T,echo=TRUE}

result <- cms_patient_experience %>% 
  pivot_wider(names_from = "measure_cd" , values_from = "prf_rate", id_cols = starts_with("org"))

result

```
